directories:
  output: release
  buildResources: build
appId: com.tictactoe.app
productName: Tic Tac Toe
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage
electronVersion: 28.3.3
